#ifndef __CORE_DEFS_H
#define __CORE_DEFS_H

#define MESSAGE_SIZE 64

#define SEND_FLAG_INTERFACE 0x0001
#define SEND_FLAG_RESPONSE  0x0002
#define SEND_FLAG_EXIT      0x0004

#define RECV_SOURCE_ANY -1

#define RECV_FLAG_RESPONSE  0x0002

#endif /*__CORE_DEFS_H*/